### ISSUE TITLE
Generator outputting different results than dev server

### ISSUE THREAD

**Issue by nehero** [statamic/ssg#31] opened 2020-08-30 18:35 UTC
Hi! First of all, my experience with Statamic 3 so far has been nothing but enjoyable. Thanks a ton for making such a flexible system 😄 

## My issue:

When developing locally and previewing using `php artisan serve` my website behaves as normal.

When I build using ssg the pages output is not the right template.

Sourcecode: https://github.com/nehero/ozzie.sh
Live: https://ozzie.sh

The home page on local is using the right template as seen here:

<img width="1615" alt="Screen Shot 2020-08-30 at 12 31 20 PM" src="https://user-images.githubusercontent.com/2093630/91666766-c3ec0e80-eabc-11ea-943e-ba5a654d85db.png">

And at the source level you can see that it is overriding the template via a field:

https://github.com/nehero/ozzie.sh/blob/master/content/collections/pages/home.md

But after generating it is displaying this:

<img width="1615" alt="Screen Shot 2020-08-30 at 12 31 26 PM" src="https://user-images.githubusercontent.com/2093630/91666775-d23a2a80-eabc-11ea-86fb-bd9b34be1b07.png">

Which is the content from a different collection called "projects"

https://github.com/nehero/ozzie.sh/blob/master/content/collections/projects/unix-time-converter.md

Let me know if there is any more info I can provide!

**Comment by jasonvarga** [comment] 2020-08-30 19:30
Your projects collection doesn't have a route, so it's being generated at `/`.

This is a duplicate of #27

**Closed by jasonvarga** 2020-08-30 19:30 UTC

**Comment by nehero** [comment] 2020-08-30 19:35
That was it, thanks!
